### ISSUE TITLE
PyEnv not respected when version checking

### ISSUE THREAD

**Issue by ajmeese7** [mxrch/GitFive#10]
I am on an Ubuntu variant, so Python 3.10 isn't natively supported. I am using PyEnv via `pyenv shell 3.10`, and as you can see below my version should be supported:

```shell
~$ gitfive login
[-] GitFive only works with Python 3.10+.
Your current Python version : 3.8.10
~$ python -V
Python 3.10.8
~$ python3 -V
Python 3.10.8
```

However, GitFive does not acknowledge that this is the case and therefore will not run.

**Comment by mxrch** [comment]
Wtf 😭 It doesn't make sense

**Comment by mxrch** [comment]
@ajmeese7 You're on which operating system ?

**Comment by mxrch** [comment]
Can you try `pipx uninstall gitfive; pipx install gitfive --python $(which python3)` ? I discovered this argument yesterday

**Comment by ajmeese7** [comment]
When I did it with `which python3.10` instead that worked! Good call. Think this is worth mentioning in the README in case anyone else has the same problem?
