### ISSUE TITLE
No JSON export documentation

### ISSUE THREAD

**Issue by ajmeese7** [mxrch/GitFive#11]
I'm very interested in using the JSON export functionality that the README and the output of the program mention, especially for the SSH keys. Could you add some documentation on how to use that feature? Usage guidelines aren't mentioned in the `--help` section or in the README anywhere as far as I can tell.

**Comment by mxrch** [comment]
Good catch, I added it in https://github.com/mxrch/GitFive/commit/7b04636785bf4f415671ccd6023488e19d8cc883 !
