### ISSUE TITLE
BUG: `Bad Credential` error when trying to use the tool

### ISSUE THREAD

**Issue by TheophileDiot** [mxrch/GitFive#29]
Steps to reproduce the bug:
`gitfive user <anyone>`

And then I get these logs:
```
[DEBUG] Cookies valid !
Request returned an unexpected status code : 401
Response : {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
```

**Comment by mxrch** [comment]
Try to `gitfive login --clean; gitfive login` and retry ?

**Comment by TheophileDiot** [comment]
@mxrch Hi sorry for not answering, I think this was because my account was banned lol.

**Comment by mxrch** [comment]
Ah yes that's a little bit relou, can you test my command stp ?

**Comment by TheophileDiot** [comment]
@mxrch Yep, I tried it and added new credentials and it works fine now :smile:
