### ISSUE TITLE
[XRAY] `Couldn't find the form to create the repo "GitFive-e6ecb6f73b794d21ac05"`

### ISSUE THREAD

**Issue by nacknime-official** [mxrch/GitFive#30]
```
🎭 IDENTITIES UNMASKING

[XRAY] 🎭 Impersonating users got in dumped commits...
Couldn't find the form to create the repo "GitFive-e6ecb6f73b794d21ac05".
```

I found out that the creating repository form has no id with value "new-repository", but only class="Box-sc-g0xbh4-0 hbENVh container-md px-md-4 px-lg-5" instead.
Seems like github has been updated recently.

Maybe just use the github API instead of parsing HTML?

**Comment by mxrch** [comment]
Did you updated to the last version ? (`pipx upgrade gitfive`)

**Comment by nacknime-official** [comment]
> Did you updated to the last version ? (`pipx upgrade gitfive`)
```
➜  ~ pipx upgrade gitfive
gitfive is already at latest version 1.1.1
```

**Comment by clowderwidely** [comment]
Also encountering this issue with gitfive on the latest version

**Comment by mxrch** [comment]
@nacknime-official @clowderwidely It should be fixed in https://github.com/mxrch/GitFive/commit/58dcc3a81ddde83f2a46b401204cda22d2f512ea, can you retry by doing `pipx upgrade gitfive` ?

**Comment by zemdkimd** [comment]
not working bro
