### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'Beta'

### ISSUE THREAD

**Issue by N0rz3** [mxrch/GitFive#38]
Salut, je ne sais pas si ce bug est aussi present chez les autres mais en essayant de lancer avec le module `user` sur mon propre profile j'ai cette erreure : 
```
total_repos = int(body.find("span", {"class": "Counter"}).attrs["title"])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Beta'
```

à cet endroit : `lib\repos.py", line 55, in get_list`

(cela ce produit lors de la partie : `🏭 REPOSITORIES STATS`) 
(j'ai Python 3.11, j'ai bien renseigné les infos demandées token, pswrd, name, j'ai essayé plusieurs fois mais le meme resultat)

merci d'avance 🙃

**Comment by N0rz3** [comment]
[NOUVELLE] apres avoir essayer de lancer le script autrement qu'avec `gitfive user N0rz3` 
j'ai essayé avec `python .\main.py user N0rz3` et la je n'ai pas eu d'erreure le script a marché parfaitement

**Comment by mxrch** [comment]
T'as pas mis à jour avec pipx

**Comment by N0rz3** [comment]
perso pipx ne marche pas quand j'installe tout est carré mais des que lance une commande avec pipx sa me dit que sa n'existe pas :/ mais c pgv je peux quand meme executer le script avec le main.py

**Comment by Steccah** [comment]
Where is the location of ./main.py?
