### ISSUE TITLE
"disclaimer" in README is incompatible with the license

### ISSUE THREAD

**Issue by maciek134** [mxrch/GitFive#4]
> The use of this tool in an automated paid service / software is strictly forbidden without my personal agreement.

This statement is incompatible with the chosen license. You should change the license to some non-OSI one, or remove the statement - restricting any type of usage is not Open Source, it's just source available and the license is misleading.

**Comment by mxrch** [comment]
Hey @maciek134, thanks for seeing this !
Which license you recommend me to use, which is compatible with the disclaimer ?

**Comment by elliotwutingfeng** [comment]
@mxrch My sincere apologies for not checking the issues page first.

For a suitable license that disallows commercial use, you could check out https://www.gnu.org/licenses/license-list.en.html#NonFreeSoftwareLicenses (most of them are marked "non-free" because of non-commercial use restrictions but that's likely what you are looking for).

**Comment by ajmeese7** [comment]
I have no dog in this fight, but I will say that if you change the license now to match what you are requesting in the README, users who use any version of the software prior to the new license will only have to abide by the license that was active in said version. So if you release a new license tomorrow, I can just clone the previous commit and as long as I don't add any of the future code updates I will still only have to follow the terms of the MPL license.

Not saying I would do so, I respect your stance on the matter :) very reasonable terms for useful free software

**Comment by mxrch** [comment]
@ajmeese7 Yes, totally... fuck licenses, businesses will always manage to steal open-source projects 🫠

**Comment by maciek134** [comment]
@mxrch you confuse open source with free (libre) software. MPL is a free software license. Free software is among other things about freedom to do anything you want with the software you receive (freedom 0), including commercial activity or even illegal stuff (a "don't use for evil" clause for example [makes the software no longer free](https://wiki.debian.org/qa.debian.org/jsonevil)).

It has nothing to do with companies or stealing - in your case no business will touch this code due to ambiguous licensing.

(btw I also have no horse in this race, I got here from Google's feed and just care about licensing clarity when it comes to free software)

**Comment by mxrch** [comment]
@maciek134  You're right ! MPL is good for free softwares only, I will consider it in my next projects. Thanks for the clarification, I appreciate it a lot !
