### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by kleozzy** [mxrch/GitFive#6]
There seems to be an issue with your login process.
I have manually verified my key with httpx and status 200 but the gitfive rejects key with 401 all the time.

Can you please check ?

**Comment by mxrch** [comment]
Hello, I can't check something with no details, it works for me and all other users I guess.
If you're sure the problem isn't on your side and you don't have sensitive informations on the Github account you're trying to link to Gitfive, maybe try to send me the key with minimum scopes in my Twitter's DM at @mxrchreborn ! And I'll can debug this.
